# Generated by Django 2.0 on 2020-07-12 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('friend_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TestApp.Profile')),
            ],
        ),
    ]
