# Generated by Django 2.0 on 2020-07-13 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friend_id',
        ),
        migrations.AddField(
            model_name='friends',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='friends',
            name='profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestApp.Profile'),
        ),
    ]
